name: Release
on: push

jobs:
  publish:
    name: Release
    runs-on: macos-latest

    steps:
    
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
    
      - name: Generate build number
        id: buildnumber
        run: |
            echo ::set-output name=version_no::$(./gradlew bumpPatch)
      - name: Get version
        run: echo "The version is ${{ steps.buildnumber.outputs.version_no }}"

