name: Release
on: push

jobs:
  publish:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Read Version Name
        run: grep "versionName" simplelibrary/build.gradle | awk '{print $2}' | tr -d \''"\'
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ grep "versionName" simplelibrary/build.gradle | awk '{print $2}' | tr -d \''"\' }}
          release_name: version ${{ grep "versionName" simplelibrary/build.gradle | awk '{print $2}' | tr -d \''"\' }}
          draft: false
          prerelease: false
