name: Release
on: push

jobs:
  publish:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Read Version Name
        id: vars
        run: |
          echo ::set-output name=version_number::"Version is $(grep "version" simplelibrary/build.gradle | awk '{print $2}' | tr -d \''"\')"
      
      - name: Set release name
        run: echo ::set-env name=RELEASE_NAME::$(echo ${GITHUB_REF:11})
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version_number }}
          release_name: version ${{ steps.vars.outputs.version_number }}
          draft: false
          prerelease: false
